### ISSUE TITLE
Suggestions for a better Trie implementation

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#106]
The `occa::trie` class used for the parser has two states:

- Non-frozen: Represents all strings as a tree with a `char` as a node through pretty much a `std::map<char, node>`
- Frozen: Represents all strings as a compact array we can use binary search in

Some issues are:
- **More memory**: We always keep the _non-frozen_ structure for edits and sync to the _frozen_ version
- **Slow GC**: Allocating and deleting all of the nodes is slow

Suggestions on how to better implement this is welcome

**Comment by pdhahn** [comment]
Please provide a bit more information. E.g., why a binary search is required (using "frozen") when there is an O(n) searchable trie available ("non-frozen")? Nearest bound / match or wildcard expansion perhaps?

**Comment by dmed256** [comment]
The trie is stored in 2 ways

### Non-frozen
A tree where each node is a `char`. For example, if we have a trie with `['cat', 'car', 'cut']` it would look like:

```
[c] +- [a] +- [r]
    |      |
    |      +- [t]
    |
    +- [u] -- [t]
```

### Frozen
The same `['cat', 'car', 'cut']` example would look like a `char[6]` holding `'caurtt'` in addition to having index and offset arrays

**Comment by pdhahn** [comment]
Tries are for dictionary operations but what do you use the "frozen" scheme for?

**Comment by dmed256** [comment]
I'm using it in the parser for "fast" string searches 
For example, checking if an identifier is a:
- Keyword
- Type
- Variable
- etc

Another example is fetching operators where we lazily read as many symbols as we can that create a valid operator, such as:
```cpp
i+++1
```
which translates to
```cpp
i++ + 1
```

🤔 In reality, I could get away with using a hashmap instead of trie for everything except the operator checks... maybe that would be the best option

**Comment by pdhahn** [comment]
OK I finally looked at your trie implementation in the source code so now I see you were not describing two different classes with the "unfrozen" and "frozen" schemes, each used for their own purposes, but rather operating modes within the same trie class. In effect, the frozen mode scheme is used like (instead of) having an actual std::map<char,node> in each trie node, which would be pretty heavyweight.

So your searches do not navigate down through the classic ("unfrozen") trie tree, making a "branch" decision for the next character at each node via either direct array indexing (costly in terms of memory) nor the std::map<char,node> thing. Instead, your searches are made on the transformed ("frozon") string(s).

**Comment by pdhahn** [comment]
I think the obvious thing is that having to maintain both "unfrozen" and "frozen" modes is not memory efficient; i.e.,  having the "frozen" mode dependent on the "unfrozen" mode in real terms contradicts the idea of a "compact" storage scheme. So frozen mode's benefit is that it achieves a non-trivial performance gain (I presume)?

**Comment by pdhahn** [comment]
A suggestion would be to abandon the "frozen" scheme in favor of the simple trie. But instead of using `std::map<char,node>`, use `std::set<node,node::order_F>` where `node::order_F` is a functor whose `bool operator()(node1,node2)` predicate compares the character (stored only in the node) in node1 vs node2. Actually, when navigating the trie, when making the branch decision at a given node, you probably should just do linear search on the leaves (i.e., iterate thru the set) when the number of leaves is small enough.

**Comment by dmed256** [comment]
Removed `trie` except for the operator to find the closest fit
