### ISSUE TITLE
Use the #include dependencies for detecting stale kernels

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#203]
Right now we only hash `properties` and file contents, but we also store all `#include` dependencies for a kernel in the preprocessor:

https://github.com/libocca/occa/blob/master/include/occa/lang/preprocessor.hpp#L84

We should add the dependencies to `build.json` and use their hashes to determine if the kernel needs to be recompiled

```js
{
  "kernel": {
    "dependencies": [
      { "source": ..., "hash": ... },
      ...,
    }
  }
}
```

**Comment by pdhahn** [comment]
In v0.2, hash checks take some time when I have a lot of kernels / OKL files. Probably the same for v1.x. As a small time saver, I use program logic to load kernels from source on demand once only when running. The only time the OCCA hash feature helps me out is between program runs if I happen to tweak some OKL code. Thus I view it as a "safety" feature, but of course, as such it is only "skin deep" since the #include's are not hashed in v0.2. So fixing that in v1.x will be most welcome.

But frankly, at least for my purposes, and maybe other folks too, instead of a hash, if auto-rebuilds were timestamp-based against OKL file dependencies, like with make, things might be better. Then the hash would not need to be unnecessarily computed again every time one does the build-from-source. Only timestamps would be checked. One step further, if the timestamp shows stale, then do the hash and check it. Namely, two levels of checking on balance may speed things up overall.

**Comment by dmed256** [comment]
For the initial kernel, I'm not sure we can get away with removing the hash check without storing the 

`filepath` &rarr; `[timestamp, hash]`

 map somewhere

However, the `[timestamp, hash]` idea seems good for the dependencies since we would already store the `filename` along with its `hash`. The only place the hash _should_ change is when the parser updates, but that would be captured with the main file's hash changing

**Comment by pdhahn** [comment]
Yes, that makes sense. Not only that, I forgot to cover the possibility that define's might change from run to run, too, although I do try hard to code in such a way that that is a rarity.

**Comment by dmed256** [comment]
This was done in #236
