### ISSUE TITLE
Add support a stream to synchronize for a specific event

### ISSUE THREAD

**Issue by deukhyun** [libocca/occa#512]
Currently only stream synchronization mechanisms available are ones equivalent to cuStreamSynchronize and cuEventSynchronize. It would be nice to have the one equivalent to cuStreamWaitEvent which can be useful to make multi-stream application more efficient.

**Comment by kris-rowe** [comment]
- CUDA: [cuStreamWaitEvent](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__STREAM.html#group__CUDA__STREAM_1g6a898b652dfc6aa1d5c8d97062618b2f)
- HIP: [hipStreamWaitEvent](https://docs.amd.com/bundle/HIP-API-Guide-v5.4.1/page/a00183.html#gacdd84c8f8ef1539c96c57c1d5bcae633)
- SYCL: [sycl::queue::ext_oneapi_submit_barrier](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_enqueue_barrier.asciidoc)
- OpenCL: [clEnqueueBarrierWithWaitList](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clEnqueueBarrierWithWaitList)
- Metal: ?

**Comment by noelchalmers** [comment]
For Metal, these might be useful:
[MTLEvent](https://developer.apple.com/documentation/metal/mtlevent)
[encodeSignalEvent](https://developer.apple.com/documentation/metal/mtlcommandbuffer/2966542-encodesignalevent)
[encodeWaitForEvent](https://developer.apple.com/documentation/metal/mtlcommandbuffer/2966543-encodewaitforevent)

See also [Synchronizing Events Within a Single Device](https://developer.apple.com/documentation/metal/resource_synchronization/synchronizing_events_within_a_single_device). I'm not volunteering to write this part, though, since I have no way to test it.

**Comment by deukhyun-cha** [comment]
I appreciate the comments. I don't have environment available for testing Metal as well, but perhaps it might be a good first step to get some build/test instruction updated from anyone running OCCA on the environment if possible (unless it's already available and I missed it). That would probably make things easier for anyone to jump-in and volunteer - including myself :)
