### ISSUE TITLE
@atomic  parser error

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#524]
```
@atomic { 
  wxy[0] += sum1;
  wxy[1] += sum2;
}
```
Error: Unable to transform general @atomic code

```
@atomic { wxy[0] += sum1; }
@atomic { wxy[1] += sum1; }
```
Works!

**Comment by kris-rowe** [comment]
It turns out that [this isn't implemented yet](
https://github.com/libocca/occa/blob/eea8fe0c1ce58a5c86cbb41ed9e2a454d8a937ac/src/occa/internal/lang/modes/cuda.cpp#L174).

Since the `@atomic` concept needs to be refined a bit further, and still has to be implemented for some of the backends (e.g., OpenCL), we will close this for now since it is covered by #118.
