### ISSUE TITLE
Passing NULL to Serial and OpenMP might fail

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#93]

**Comment by dmed256** [comment]
@pdhahn In the addVectors example, this worked for me:
```c++
addVectors(entries, o_a, (void*) NULL, o_ab);
```
and switching the `.okl` kernel to:
```c++
ab[i] = a[i] + a[i];
```
Do you have a reproducible example I can look at?

**Comment by pdhahn** [comment]
It seems to only happen for non-const FLOAT* arg pointers. So fo example, try modifying addVectors.okl thus:
`if  (ab)
    ab[i]  = a[i] + b[i];`
I have this situation because I want to have "optional" outputs computed by certain kernels. By design, if the array arg is NULL, the kernel should not compute it.

**Comment by pdhahn** [comment]
A NULL pointer used like this works fine for OpenCL (at least, for GPU). I've been relying on that for a very long time now. But the crash happens for Serial and OpenMP. Haven't checked CUDA or OpenCL on CPU.

**Comment by pdhahn** [comment]
Hmmm, now I am in OCCA 0.2 and I cannot reproduce it. I will keep checking.

**Comment by dmed256** [comment]
No worries, glad it was resolved at some point :)

**Comment by pdhahn** [comment]
OK I have figured it out now, actually. I was passing '0' (zero) for the pointer arg instead of '(void*)0'. For OpenCL, '0' seems to be interpreted as '(void*)0'. For Serial and OpenMP, '0' is interpreted as an int arg. I can see this when I set OCCA_CXX to 'g++ -g' (add debug flag) then step into the Serial kernel while in gdb. The args to _MyKernel_(...)  are non-null in this case.

I just verified this using the addVectors example in 0.2, for the 'ab' (result) arg.

**Comment by pdhahn** [comment]
So the programmer (e.g., me) just needs to be careful to cast the arg properly, since it is a pointer after all. In the worst case, I think this just means this issue should be relegated to the "insufficient bulletproofing against poor user programming" category. :-)

**Comment by dmed256** [comment]
Not having type testing can lead to annoying bugs, I opened up #95 to add some type of checks in the future
